galaxy_info:
  author: Ean Wilson
  description: This role discovers Redfish inventory from BMCs and writes YAML reports.
  company: Rockwell Automation

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  license: MIT

  min_ansible_version: 2.17.14

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags:
    - discovery
    - baremetal
    - redfish
    - idrac
    - bmc
    - ilo

dependencies: []
